services:
  sender:
    build:
      context: ../../
      dockerfile: ./01_Code/4_Docker/sender/Dockerfile
    networks:
      - latency_test_network
    depends_on:
      - receiver

  receiver:
    build:
      context: ./receiver
      dockerfile: Dockerfile
    networks:
      - latency_test_network

networks:
  latency_test_network:
    driver: bridge
